use_frameworks!

abstract_target 'Demo' do
  pod 'RealmSwift'
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxRealm'
  pod 'RxRealmDataSources', :path => '../'

  target 'RxRealmDataSources_Example' do
    platform :ios, '9.0'
  end

  target 'RxRealmDataSources_MacExample' do
    platform :osx, '10.12'
  end
end
